// Code generated by "stringer -type ComponentUpdateStatus -trimprefix ComponentUpdateStatus"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentUpdateStatusPause-0]
	_ = x[ComponentUpdateStatusOnSchedule-1]
	_ = x[ComponentUpdateStatusNotSupported-2]
}

const _ComponentUpdateStatus_name = "PauseOnScheduleNotSupported"

var _ComponentUpdateStatus_index = [...]uint8{0, 5, 15, 27}

func (i ComponentUpdateStatus) String() string {
	if i < 0 || i >= ComponentUpdateStatus(len(_ComponentUpdateStatus_index)-1) {
		return "ComponentUpdateStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentUpdateStatus_name[_ComponentUpdateStatus_index[i]:_ComponentUpdateStatus_index[i+1]]
}
