// Code generated by "stringer -type ComponentVersion -trimprefix ComponentVersion"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentVersionOutdatedVersion-0]
	_ = x[ComponentVersionLatestVersion-1]
	_ = x[ComponentVersionControlledLatestVersion-2]
	_ = x[ComponentVersionUnknownVersions-3]
}

const _ComponentVersion_name = "OutdatedVersionLatestVersionControlledLatestVersionUnknownVersions"

var _ComponentVersion_index = [...]uint8{0, 15, 28, 51, 66}

func (i ComponentVersion) String() string {
	if i < 0 || i >= ComponentVersion(len(_ComponentVersion_index)-1) {
		return "ComponentVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentVersion_name[_ComponentVersion_index[i]:_ComponentVersion_index[i+1]]
}
