// Code generated by "stringer -type DataSource -trimprefix DataSource"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Detections-0]
	_ = x[EndpointActivityData-1]
	_ = x[CloudActivityData-2]
	_ = x[EmailActivityData-3]
	_ = x[MobileActivityData-4]
	_ = x[NetworkActivityData-5]
	_ = x[ContainerActivityData-6]
	_ = x[IdentityActivityData-7]
	_ = x[ThirdPartyLogData-8]
}

const _DataSource_name = "DetectionsEndpointActivityDataCloudActivityDataEmailActivityDataMobileActivityDataNetworkActivityDataContainerActivityDataIdentityActivityDataThirdPartyLogData"

var _DataSource_index = [...]uint8{0, 10, 30, 47, 64, 82, 101, 122, 142, 159}

func (i DataSource) String() string {
	if i < 0 || i >= DataSource(len(_DataSource_index)-1) {
		return "DataSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSource_name[_DataSource_index[i]:_DataSource_index[i+1]]
}
