// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package=vone -type=InvestigationResult -names No Findings,Noteworthy,True Positive,False Positive,Benign True Positive,Other Findings
// DO NOT EDIT!

package vone

import (
    "encoding/json"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type InvestigationResult int

const (
    InvestigationResultNo_Findings          InvestigationResult = iota
    InvestigationResultNoteworthy           InvestigationResult = iota
    InvestigationResultTrue_Positive        InvestigationResult = iota
    InvestigationResultFalse_Positive       InvestigationResult = iota
    InvestigationResultBenign_True_Positive InvestigationResult = iota
    InvestigationResultOther_Findings       InvestigationResult = iota
)



// MapInvestigationResultToString - map InvestigationResult to string
var MapInvestigationResultToString = map[InvestigationResult]string {
    InvestigationResultNo_Findings:          "No Findings",
    InvestigationResultNoteworthy:           "Noteworthy",
    InvestigationResultTrue_Positive:        "True Positive",
    InvestigationResultFalse_Positive:       "False Positive",
    InvestigationResultBenign_True_Positive: "Benign True Positive",
    InvestigationResultOther_Findings:       "Other Findings",
}

// String - return string representation for InvestigationResult value
func (v InvestigationResult)String() string {
    s, ok := MapInvestigationResultToString[v]
    if ok {
        return s
    }
    return "InvestigationResult(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownInvestigationResult - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownInvestigationResult = errors.New("unknown InvestigationResult")

 // MapInvestigationResultFromString - map string to InvestigationResult value
var MapInvestigationResultFromString = map[string]InvestigationResult{
    "no findings":    InvestigationResultNo_Findings,
    "noteworthy":    InvestigationResultNoteworthy,
    "true positive":    InvestigationResultTrue_Positive,
    "false positive":    InvestigationResultFalse_Positive,
    "benign true positive":    InvestigationResultBenign_True_Positive,
    "other findings":    InvestigationResultOther_Findings,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for InvestigationResult.
func (s *InvestigationResult) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := MapInvestigationResultFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownInvestigationResult, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for InvestigationResult.
func (s InvestigationResult) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for InvestigationResult.
func (s *InvestigationResult) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := MapInvestigationResultFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownInvestigationResult, v)
    }
    *s = result
    return nil
}


// MarshalYAML implements the Marshaler interface of the yaml.v3 package for InvestigationResult.
func (s InvestigationResult) MarshalYAML() (interface{}, error) {
    return s.String(), nil
}
