// Code generated by enum (github.com/mpkondrashin/enum). DO NOT EDIT

package vone

import (
    "encoding/json"
    "fmt"
    "strconv"
)

type RiskLevel int

const (
    RiskLevelHigh RiskLevel = iota
    RiskLevelMedium RiskLevel = iota
    RiskLevelLow RiskLevel = iota
    RiskLevelNoRisk RiskLevel = iota
)

func (v RiskLevel)String() string {
    s, ok := map[RiskLevel]string {
        RiskLevelHigh: "high",
        RiskLevelMedium: "medium",
        RiskLevelLow: "low",
        RiskLevelNoRisk: "noRisk",
    }[v]
    if ok {
        return s
    }
    return "RiskLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}

func (s *RiskLevel) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := map[string]RiskLevel{
        "high": RiskLevelHigh,
        "medium": RiskLevelMedium,
        "low": RiskLevelLow,
        "noRisk": RiskLevelNoRisk,
    }[v]
    if !ok {
        return fmt.Errorf("%w: %s", ErrEnumUnknown, v)
    }
    *s = result
    return nil
}
