// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package=vone -type=Mode -names default,countOnly,performance
// DO NOT EDIT!

package vone

import (
    "encoding/json"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type Mode int

const (
    ModeDefault     Mode = iota
    ModeCountOnly   Mode = iota
    ModePerformance Mode = iota
)



// MapModeToString - map Mode to string
var MapModeToString = map[Mode]string {
    ModeDefault:     "default",
    ModeCountOnly:   "countOnly",
    ModePerformance: "performance",
}

// String - return string representation for Mode value
func (v Mode)String() string {
    s, ok := MapModeToString[v]
    if ok {
        return s
    }
    return "Mode(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownMode - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownMode = errors.New("unknown Mode")

 // MapModeFromString - map string to Mode value
var MapModeFromString = map[string]Mode{
    "default":    ModeDefault,
    "countonly":    ModeCountOnly,
    "performance":    ModePerformance,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for Mode.
func (s *Mode) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := MapModeFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownMode, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for Mode.
func (s Mode) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for Mode.
func (s *Mode) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := MapModeFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownMode, v)
    }
    *s = result
    return nil
}


// MarshalYAML implements the Marshaler interface of the yaml.v3 package for Mode.
func (s Mode) MarshalYAML() (interface{}, error) {
    return s.String(), nil
}
