// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package=vone -type=DateTimeTarget -noprefix -names CreatedDateTime,LastActionDateTime
// DO NOT EDIT!

package vone

import (
    "encoding/json"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type DateTimeTarget int

const (
    CreatedDateTime    DateTimeTarget = iota
    LastActionDateTime DateTimeTarget = iota
)



// MapDateTimeTargetToString - map DateTimeTarget to string
var MapDateTimeTargetToString = map[DateTimeTarget]string {
    CreatedDateTime:    "CreatedDateTime",
    LastActionDateTime: "LastActionDateTime",
}

// String - return string representation for DateTimeTarget value
func (v DateTimeTarget)String() string {
    s, ok := MapDateTimeTargetToString[v]
    if ok {
        return s
    }
    return "DateTimeTarget(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownDateTimeTarget - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownDateTimeTarget = errors.New("unknown DateTimeTarget")

 // MapDateTimeTargetFromString - map string to DateTimeTarget value
var MapDateTimeTargetFromString = map[string]DateTimeTarget{
    "createddatetime":    CreatedDateTime,
    "lastactiondatetime":    LastActionDateTime,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for DateTimeTarget.
func (s *DateTimeTarget) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := MapDateTimeTargetFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownDateTimeTarget, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for DateTimeTarget.
func (s DateTimeTarget) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for DateTimeTarget.
func (s *DateTimeTarget) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := MapDateTimeTargetFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownDateTimeTarget, v)
    }
    *s = result
    return nil
}


// MarshalYAML implements the Marshaler interface of the yaml.v3 package for DateTimeTarget.
func (s DateTimeTarget) MarshalYAML() (interface{}, error) {
    return s.String(), nil
}
