// Code generated by enum (github.com/mpkondrashin/enum) using following command:
// enum -package=vone -type=AlertStatus -names=Open,InProgress,Closed
// DO NOT EDIT!

package vone

import (
    "encoding/json"
    "errors"
    "fmt"
    "strconv"
    "strings"
)

type AlertStatus int

const (
    AlertStatusOpen       AlertStatus = iota
    AlertStatusInProgress AlertStatus = iota
    AlertStatusClosed     AlertStatus = iota
)



// MapAlertStatusToString - map AlertStatus to string
var MapAlertStatusToString = map[AlertStatus]string {
    AlertStatusOpen:       "Open",
    AlertStatusInProgress: "InProgress",
    AlertStatusClosed:     "Closed",
}

// String - return string representation for AlertStatus value
func (v AlertStatus)String() string {
    s, ok := MapAlertStatusToString[v]
    if ok {
        return s
    }
    return "AlertStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}

// ErrUnknownAlertStatus - will be returned wrapped when parsing string
// containing unrecognized value.
var ErrUnknownAlertStatus = errors.New("unknown AlertStatus")

 // MapAlertStatusFromString - map string to AlertStatus value
var MapAlertStatusFromString = map[string]AlertStatus{
    "open":    AlertStatusOpen,
    "inprogress":    AlertStatusInProgress,
    "closed":    AlertStatusClosed,
}

// UnmarshalJSON implements the Unmarshaler interface of the json package for AlertStatus.
func (s *AlertStatus) UnmarshalJSON(data []byte) error {
    var v string
    if err := json.Unmarshal(data, &v); err != nil {
        return err
    }
    result, ok := MapAlertStatusFromString[strings.ToLower(v)]
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownAlertStatus, v)
    }
    *s = result
    return nil
}

// MarshalJSON implements the Marshaler interface of the json package for AlertStatus.
func (s AlertStatus) MarshalJSON() ([]byte, error) {
    return []byte(fmt.Sprintf("\"%v\"", s)), nil
}

// UnmarshalYAML implements the Unmarshaler interface of the yaml.v3 package for AlertStatus.
func (s *AlertStatus) UnmarshalYAML(unmarshal func(interface{}) error) error {
    var v string
    if err := unmarshal(&v); err != nil {
        return err
    }
    result, ok := MapAlertStatusFromString[strings.ToLower(v)]  
    if !ok {
        return fmt.Errorf("%w: %s", ErrUnknownAlertStatus, v)
    }
    *s = result
    return nil
}


// MarshalYAML implements the Marshaler interface of the yaml.v3 package for AlertStatus.
func (s AlertStatus) MarshalYAML() (interface{}, error) {
    return s.String(), nil
}
