// Code generated by "stringer -type EventID -trimprefix EventID"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EVENT_PROCESS-1]
	_ = x[EVENT_FILE-2]
	_ = x[EVENT_CONNECTIO-3]
	_ = x[EVENT_DNS-4]
	_ = x[EVENT_REGISTRY-5]
	_ = x[EVENT_ACCOUNT-6]
	_ = x[EVENT_INTERNET-7]
	_ = x[XDR_EVENT_MODIFIED_PROCESS-8]
	_ = x[EVENT_WINDOWS_HOOK-9]
	_ = x[EVENT_WINDOWS_EVENT-10]
	_ = x[EVENT_AMSI-11]
	_ = x[EVENT_WMI-12]
	_ = x[TELEMETRY_MEMORY-13]
	_ = x[TELEMETRY_BM-14]
}

const _EventID_name = "EVENT_PROCESSEVENT_FILEEVENT_CONNECTIOEVENT_DNSEVENT_REGISTRYEVENT_ACCOUNTEVENT_INTERNETXDR_EVENT_MODIFIED_PROCESSEVENT_WINDOWS_HOOKEVENT_WINDOWS_EVENTEVENT_AMSIEVENT_WMITELEMETRY_MEMORYTELEMETRY_BM"

var _EventID_index = [...]uint8{0, 13, 23, 38, 47, 61, 74, 88, 114, 132, 151, 161, 170, 186, 198}

func (i EventID) String() string {
	i -= 1
	if i < 0 || i >= EventID(len(_EventID_index)-1) {
		return "EventID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventID_name[_EventID_index[i]:_EventID_index[i+1]]
}
