// Code generated by "stringer -type Field -trimprefix Field"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldAgentGuid-0]
	_ = x[FieldLoginAccount-1]
	_ = x[FieldEndpointName-2]
	_ = x[FieldMACAddress-3]
	_ = x[FieldIP-4]
	_ = x[FieldProtectionManager-5]
	_ = x[FieldPolicyName-6]
	_ = x[FieldComponentUpdatePolicy-7]
	_ = x[FieldComponentUpdateStatus-8]
	_ = x[FieldComponentVersion-9]
	_ = x[FieldOSName-10]
	_ = x[FieldOSVersion-11]
	_ = x[FieldProductCode-12]
	_ = x[FieldInstalledProductCodes-13]
}

const _Field_name = "AgentGuidLoginAccountEndpointNameMACAddressIPProtectionManagerPolicyNameComponentUpdatePolicyComponentUpdateStatusComponentVersionOSNameOSVersionProductCodeInstalledProductCodes"

var _Field_index = [...]uint8{0, 9, 21, 33, 43, 45, 62, 72, 93, 114, 130, 136, 145, 156, 177}

func (i Field) String() string {
	if i < 0 || i >= Field(len(_Field_index)-1) {
		return "Field(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_name[_Field_index[i]:_Field_index[i+1]]
}
