// Code generated by "stringer -type ObjectSubTrueType -trimprefix ObjectSubTrueType"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MSOfficeOrUnknownOLE-1000]
	_ = x[Winword20-1001]
	_ = x[Winword10-1002]
	_ = x[HangulWordProcessor-1003]
	_ = x[Ichitaro-1004]
	_ = x[JungUmGlobal-1005]
	_ = x[OutlookItem-1006]
	_ = x[MSPublisher-1007]
	_ = x[MSOffice-4000]
	_ = x[HancomHancell-4001]
	_ = x[UnknownTypeMSOffice2007-4045000]
	_ = x[WordMSOffice2007-4045001]
	_ = x[ExcelMSOffice2007-4045002]
	_ = x[PTTMSOffice2007-4045003]
	_ = x[XPSOffice2007-4045004]
	_ = x[HwpStandardOWPMLDocument-1004000]
	_ = x[UnknownXMLDocument-1003000]
	_ = x[Word2003XMLDocument-1003001]
	_ = x[XMLSpreadsheet2003-1003002]
	_ = x[PowerPointXMLPresentation-1003003]
	_ = x[FLI-22000]
	_ = x[FLC-22001]
	_ = x[FLIC-22002]
	_ = x[WindowsWrite-16000]
	_ = x[WordForDOS-16001]
	_ = x[DOS_EXE-7000]
	_ = x[WIN16_EXE-7001]
	_ = x[WIN32_EXE-7002]
	_ = x[OS2_EXE-7003]
	_ = x[WIN16_DLL-7004]
	_ = x[Win32_DLL-7005]
	_ = x[WindowsVxD-7006]
	_ = x[OS2_2xVxD-7007]
	_ = x[NT_MIPS_EXE-7008]
	_ = x[PKLITE_EXE-7009]
	_ = x[LZEXE-7010]
	_ = x[DIET_EXE-7011]
	_ = x[PKZIP_EXE-7012]
	_ = x[ARJ_EXE-7013]
	_ = x[LZH_EXE-7014]
	_ = x[LZH_EXE_UsedByZipMail-7015]
	_ = x[ASPACK-7016]
	_ = x[UPX_EXE-7017]
	_ = x[MSIL-7018]
	_ = x[ASPACK2x-7019]
	_ = x[WWPACK-7020]
	_ = x[PETITE-7021]
	_ = x[PEPACK-7022]
	_ = x[MEW11-7023]
	_ = x[MEW05-7024]
	_ = x[MEW10-7025]
	_ = x[AMD64_EXE-7026]
	_ = x[AMD64_DLL-7027]
	_ = x[ARM_EXE-7028]
	_ = x[THUMB_EXE-7029]
	_ = x[Miscellaneous_EXE-7030]
	_ = x[UPX64-7031]
	_ = x[DLLNotProgram-7032]
	_ = x[DOS_COM-5000]
	_ = x[PKLITE_COM-5001]
	_ = x[DIET_COM-5002]
	_ = x[LZH_COM-5003]
	_ = x[ELFFile-19000]
	_ = x[ELFReloactableFile-19001]
	_ = x[ELFEXEFile-19002]
	_ = x[ELFLibraryFile-19003]
	_ = x[ELFCoredumpFile-19004]
	_ = x[EPOCBinaryFile-126000]
	_ = x[EPOCEXEFile-126001]
	_ = x[EPOCLibraryFile-126002]
	_ = x[EPOCCompressedFile-126003]
	_ = x[SISFile-128000]
	_ = x[SISFileAlt-128001]
	_ = x[PDF-6015000]
	_ = x[ISO9660File-1005000]
	_ = x[UDFFile-1005001]
	_ = x[FrameMakerDocumentFile-6004000]
	_ = x[FrameMakerMIFFile-6004001]
	_ = x[FrameMakerMMLFile-6004002]
	_ = x[FrameMakerBookFile-6004003]
	_ = x[FrameMakerDictionaryFile-6004004]
	_ = x[FrameMakerFontFile-6004005]
	_ = x[FrameMakerIPL-6004006]
	_ = x[AdobeFontMetrics-6001000]
	_ = x[AdobeFontBits-6001001]
	_ = x[AVI-4020000]
	_ = x[WAV-4020001]
	_ = x[BND-4020002]
	_ = x[RMI-4020003]
	_ = x[RDI-4020004]
	_ = x[CDA-4020005]
	_ = x[ANI-4020006]
	_ = x[CMX-4020007]
	_ = x[Compressed16Bits-2004000]
	_ = x[PackedData-2004001]
	_ = x[CompackedData-2004002]
	_ = x[SCOCompressed-2004003]
	_ = x[ScriptVBScriptJavascript-28000]
	_ = x[HTMLFile-28001]
	_ = x[PALMResourceCodeFile-28002]
	_ = x[ASPFile-28003]
	_ = x[GeneralTextFile-28004]
	_ = x[ActionScript-28005]
	_ = x[XMLDataPackage-28006]
	_ = x[MACBIN-115000]
	_ = x[AutoCADDWG-58000]
	_ = x[AutoCADR2000-58001]
	_ = x[MBX_OUTLOOK4-116000]
	_ = x[MBX_Unix-116001]
	_ = x[MBX_FOXMAIL-116002]
	_ = x[MSAccessMDB-26000]
	_ = x[MSAccess2000XP-26001]
	_ = x[MSAccessMDB20-26002]
	_ = x[MSAccess2007-26003]
	_ = x[OutlookMSOFile-6016000]
	_ = x[ExchangeMSOData-6016001]
	_ = x[UnknownOpenDocumentFile-4048000]
	_ = x[OpenDocumentTextFile-4048001]
	_ = x[OpenDocumentGraphicFile-4048002]
	_ = x[OpenDocumentPresentationFile-4048003]
	_ = x[OpenDocumentSpreadsheetFile-4048004]
	_ = x[OpenDocumentFormulaFile-4048005]
	_ = x[OpenDocumentDatabaseFile-4048006]
	_ = x[UncompressedSWF-4038000]
	_ = x[CompressedSWF-4038001]
	_ = x[LZMACompressedSWF-4038002]
	_ = x[UnknownMatchObjectFile-4052000]
	_ = x[X86MatchObjectFile-4052001]
	_ = x[X64MatchObjectFile-4052002]
	_ = x[ONENOTE_ONE-4055000]
	_ = x[ONENOTE_ONETOC2-4055001]
	_ = x[ONENOTE_ONE_FSSHTTP-4055002]
	_ = x[ONENOTE_ONETOC2_FSSHTTP-4055003]
	_ = x[FILESS_REG-8000001]
	_ = x[FILESS_WMI-8000002]
	_ = x[FILESS_SCHEDULE_TASK-8000003]
	_ = x[FILESS_AMSI-8000004]
	_ = x[FILESS_MIP3-8000005]
	_ = x[FILESS_CMD-8000006]
	_ = x[FILESS_MIP3_X86_64-8000007]
}

const _ObjectSubTrueType_name = "MSOfficeOrUnknownOLEWinword20Winword10HangulWordProcessorIchitaroJungUmGlobalOutlookItemMSPublisherMSOfficeHancomHancellDOS_COMPKLITE_COMDIET_COMLZH_COMDOS_EXEWIN16_EXEWIN32_EXEOS2_EXEWIN16_DLLWin32_DLLWindowsVxDOS2_2xVxDNT_MIPS_EXEPKLITE_EXELZEXEDIET_EXEPKZIP_EXEARJ_EXELZH_EXELZH_EXE_UsedByZipMailASPACKUPX_EXEMSILASPACK2xWWPACKPETITEPEPACKMEW11MEW05MEW10AMD64_EXEAMD64_DLLARM_EXETHUMB_EXEMiscellaneous_EXEUPX64DLLNotProgramWindowsWriteWordForDOSELFFileELFReloactableFileELFEXEFileELFLibraryFileELFCoredumpFileFLIFLCFLICMSAccessMDBMSAccess2000XPMSAccessMDB20MSAccess2007ScriptVBScriptJavascriptHTMLFilePALMResourceCodeFileASPFileGeneralTextFileActionScriptXMLDataPackageAutoCADDWGAutoCADR2000MACBINMBX_OUTLOOK4MBX_UnixMBX_FOXMAILEPOCBinaryFileEPOCEXEFileEPOCLibraryFileEPOCCompressedFileSISFileSISFileAltUnknownXMLDocumentWord2003XMLDocumentXMLSpreadsheet2003PowerPointXMLPresentationHwpStandardOWPMLDocumentISO9660FileUDFFileCompressed16BitsPackedDataCompackedDataSCOCompressedAVIWAVBNDRMIRDICDAANICMXUncompressedSWFCompressedSWFLZMACompressedSWFUnknownTypeMSOffice2007WordMSOffice2007ExcelMSOffice2007PTTMSOffice2007XPSOffice2007UnknownOpenDocumentFileOpenDocumentTextFileOpenDocumentGraphicFileOpenDocumentPresentationFileOpenDocumentSpreadsheetFileOpenDocumentFormulaFileOpenDocumentDatabaseFileUnknownMatchObjectFileX86MatchObjectFileX64MatchObjectFileONENOTE_ONEONENOTE_ONETOC2ONENOTE_ONE_FSSHTTPONENOTE_ONETOC2_FSSHTTPAdobeFontMetricsAdobeFontBitsFrameMakerDocumentFileFrameMakerMIFFileFrameMakerMMLFileFrameMakerBookFileFrameMakerDictionaryFileFrameMakerFontFileFrameMakerIPLPDFOutlookMSOFileExchangeMSODataFILESS_REGFILESS_WMIFILESS_SCHEDULE_TASKFILESS_AMSIFILESS_MIP3FILESS_CMDFILESS_MIP3_X86_64"

var _ObjectSubTrueType_map = map[ObjectSubTrueType]string{
	1000:    _ObjectSubTrueType_name[0:20],
	1001:    _ObjectSubTrueType_name[20:29],
	1002:    _ObjectSubTrueType_name[29:38],
	1003:    _ObjectSubTrueType_name[38:57],
	1004:    _ObjectSubTrueType_name[57:65],
	1005:    _ObjectSubTrueType_name[65:77],
	1006:    _ObjectSubTrueType_name[77:88],
	1007:    _ObjectSubTrueType_name[88:99],
	4000:    _ObjectSubTrueType_name[99:107],
	4001:    _ObjectSubTrueType_name[107:120],
	5000:    _ObjectSubTrueType_name[120:127],
	5001:    _ObjectSubTrueType_name[127:137],
	5002:    _ObjectSubTrueType_name[137:145],
	5003:    _ObjectSubTrueType_name[145:152],
	7000:    _ObjectSubTrueType_name[152:159],
	7001:    _ObjectSubTrueType_name[159:168],
	7002:    _ObjectSubTrueType_name[168:177],
	7003:    _ObjectSubTrueType_name[177:184],
	7004:    _ObjectSubTrueType_name[184:193],
	7005:    _ObjectSubTrueType_name[193:202],
	7006:    _ObjectSubTrueType_name[202:212],
	7007:    _ObjectSubTrueType_name[212:221],
	7008:    _ObjectSubTrueType_name[221:232],
	7009:    _ObjectSubTrueType_name[232:242],
	7010:    _ObjectSubTrueType_name[242:247],
	7011:    _ObjectSubTrueType_name[247:255],
	7012:    _ObjectSubTrueType_name[255:264],
	7013:    _ObjectSubTrueType_name[264:271],
	7014:    _ObjectSubTrueType_name[271:278],
	7015:    _ObjectSubTrueType_name[278:299],
	7016:    _ObjectSubTrueType_name[299:305],
	7017:    _ObjectSubTrueType_name[305:312],
	7018:    _ObjectSubTrueType_name[312:316],
	7019:    _ObjectSubTrueType_name[316:324],
	7020:    _ObjectSubTrueType_name[324:330],
	7021:    _ObjectSubTrueType_name[330:336],
	7022:    _ObjectSubTrueType_name[336:342],
	7023:    _ObjectSubTrueType_name[342:347],
	7024:    _ObjectSubTrueType_name[347:352],
	7025:    _ObjectSubTrueType_name[352:357],
	7026:    _ObjectSubTrueType_name[357:366],
	7027:    _ObjectSubTrueType_name[366:375],
	7028:    _ObjectSubTrueType_name[375:382],
	7029:    _ObjectSubTrueType_name[382:391],
	7030:    _ObjectSubTrueType_name[391:408],
	7031:    _ObjectSubTrueType_name[408:413],
	7032:    _ObjectSubTrueType_name[413:426],
	16000:   _ObjectSubTrueType_name[426:438],
	16001:   _ObjectSubTrueType_name[438:448],
	19000:   _ObjectSubTrueType_name[448:455],
	19001:   _ObjectSubTrueType_name[455:473],
	19002:   _ObjectSubTrueType_name[473:483],
	19003:   _ObjectSubTrueType_name[483:497],
	19004:   _ObjectSubTrueType_name[497:512],
	22000:   _ObjectSubTrueType_name[512:515],
	22001:   _ObjectSubTrueType_name[515:518],
	22002:   _ObjectSubTrueType_name[518:522],
	26000:   _ObjectSubTrueType_name[522:533],
	26001:   _ObjectSubTrueType_name[533:547],
	26002:   _ObjectSubTrueType_name[547:560],
	26003:   _ObjectSubTrueType_name[560:572],
	28000:   _ObjectSubTrueType_name[572:596],
	28001:   _ObjectSubTrueType_name[596:604],
	28002:   _ObjectSubTrueType_name[604:624],
	28003:   _ObjectSubTrueType_name[624:631],
	28004:   _ObjectSubTrueType_name[631:646],
	28005:   _ObjectSubTrueType_name[646:658],
	28006:   _ObjectSubTrueType_name[658:672],
	58000:   _ObjectSubTrueType_name[672:682],
	58001:   _ObjectSubTrueType_name[682:694],
	115000:  _ObjectSubTrueType_name[694:700],
	116000:  _ObjectSubTrueType_name[700:712],
	116001:  _ObjectSubTrueType_name[712:720],
	116002:  _ObjectSubTrueType_name[720:731],
	126000:  _ObjectSubTrueType_name[731:745],
	126001:  _ObjectSubTrueType_name[745:756],
	126002:  _ObjectSubTrueType_name[756:771],
	126003:  _ObjectSubTrueType_name[771:789],
	128000:  _ObjectSubTrueType_name[789:796],
	128001:  _ObjectSubTrueType_name[796:806],
	1003000: _ObjectSubTrueType_name[806:824],
	1003001: _ObjectSubTrueType_name[824:843],
	1003002: _ObjectSubTrueType_name[843:861],
	1003003: _ObjectSubTrueType_name[861:886],
	1004000: _ObjectSubTrueType_name[886:910],
	1005000: _ObjectSubTrueType_name[910:921],
	1005001: _ObjectSubTrueType_name[921:928],
	2004000: _ObjectSubTrueType_name[928:944],
	2004001: _ObjectSubTrueType_name[944:954],
	2004002: _ObjectSubTrueType_name[954:967],
	2004003: _ObjectSubTrueType_name[967:980],
	4020000: _ObjectSubTrueType_name[980:983],
	4020001: _ObjectSubTrueType_name[983:986],
	4020002: _ObjectSubTrueType_name[986:989],
	4020003: _ObjectSubTrueType_name[989:992],
	4020004: _ObjectSubTrueType_name[992:995],
	4020005: _ObjectSubTrueType_name[995:998],
	4020006: _ObjectSubTrueType_name[998:1001],
	4020007: _ObjectSubTrueType_name[1001:1004],
	4038000: _ObjectSubTrueType_name[1004:1019],
	4038001: _ObjectSubTrueType_name[1019:1032],
	4038002: _ObjectSubTrueType_name[1032:1049],
	4045000: _ObjectSubTrueType_name[1049:1072],
	4045001: _ObjectSubTrueType_name[1072:1088],
	4045002: _ObjectSubTrueType_name[1088:1105],
	4045003: _ObjectSubTrueType_name[1105:1120],
	4045004: _ObjectSubTrueType_name[1120:1133],
	4048000: _ObjectSubTrueType_name[1133:1156],
	4048001: _ObjectSubTrueType_name[1156:1176],
	4048002: _ObjectSubTrueType_name[1176:1199],
	4048003: _ObjectSubTrueType_name[1199:1227],
	4048004: _ObjectSubTrueType_name[1227:1254],
	4048005: _ObjectSubTrueType_name[1254:1277],
	4048006: _ObjectSubTrueType_name[1277:1301],
	4052000: _ObjectSubTrueType_name[1301:1323],
	4052001: _ObjectSubTrueType_name[1323:1341],
	4052002: _ObjectSubTrueType_name[1341:1359],
	4055000: _ObjectSubTrueType_name[1359:1370],
	4055001: _ObjectSubTrueType_name[1370:1385],
	4055002: _ObjectSubTrueType_name[1385:1404],
	4055003: _ObjectSubTrueType_name[1404:1427],
	6001000: _ObjectSubTrueType_name[1427:1443],
	6001001: _ObjectSubTrueType_name[1443:1456],
	6004000: _ObjectSubTrueType_name[1456:1478],
	6004001: _ObjectSubTrueType_name[1478:1495],
	6004002: _ObjectSubTrueType_name[1495:1512],
	6004003: _ObjectSubTrueType_name[1512:1530],
	6004004: _ObjectSubTrueType_name[1530:1554],
	6004005: _ObjectSubTrueType_name[1554:1572],
	6004006: _ObjectSubTrueType_name[1572:1585],
	6015000: _ObjectSubTrueType_name[1585:1588],
	6016000: _ObjectSubTrueType_name[1588:1602],
	6016001: _ObjectSubTrueType_name[1602:1617],
	8000001: _ObjectSubTrueType_name[1617:1627],
	8000002: _ObjectSubTrueType_name[1627:1637],
	8000003: _ObjectSubTrueType_name[1637:1657],
	8000004: _ObjectSubTrueType_name[1657:1668],
	8000005: _ObjectSubTrueType_name[1668:1679],
	8000006: _ObjectSubTrueType_name[1679:1689],
	8000007: _ObjectSubTrueType_name[1689:1707],
}

func (i ObjectSubTrueType) String() string {
	if str, ok := _ObjectSubTrueType_map[i]; ok {
		return str
	}
	return "ObjectSubTrueType(" + strconv.FormatInt(int64(i), 10) + ")"
}
