// Code generated by "stringer -type ProductCode -trimprefix ProductCode"; DO NOT EDIT.

package vone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProductCodeSAO-0]
	_ = x[ProductCodeSDS-1]
	_ = x[ProductCodeXES-2]
}

const _ProductCode_name = "SAOSDSXES"

var _ProductCode_index = [...]uint8{0, 3, 6, 9}

func (i ProductCode) String() string {
	if i < 0 || i >= ProductCode(len(_ProductCode_index)-1) {
		return "ProductCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProductCode_name[_ProductCode_index[i]:_ProductCode_index[i+1]]
}
