#
# VOne (c) 2023 by Michael Kondrashin (mkondrashin@gmail.com)
# Copyright under MIT Lincese. Please see LICENSE file for details
#
# build.yml - github actions file to build release
#

name: Build
on: [push]
jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Check Go version
        run: go version
      - name: Get enum
        run: go get github.com/mpkondrashin/enum
      - name: Install enum
        run: go install github.com/mpkondrashin/enum
      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go generate
          GOOS=linux GOARCH=amd64 go build ./cmd/vone
          GOOS=linux GOARCH=amd64 go build ./cmd/region
          tar cfvz vone_linux_amd64.tgz vone region
          GOOS=darwin GOARCH=amd64 go build ./cmd/vone
          GOOS=darwin GOARCH=amd64 go build ./cmd/region
          tar cfvz vone_darwin_amd64.tgz vone region
          GOOS=darwin GOARCH=arm64 go build ./cmd/vone
          GOOS=darwin GOARCH=arm64 go build ./cmd/region
          tar cfvz vone_darwin_arm64.tgz vone region
          GOOS=windows GOARCH=amd64 go build ./cmd/vone
          GOOS=windows GOARCH=amd64 go build ./cmd/region
          tar cfvz vone_windows_amd64.tgz vone.exe region.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vone_linux_amd64.tgz
            vone_darwin_amd64.tgz
            vone_darwin_arm64.tgz
            vone_windows_amd64.tgz
